import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./(NextClient)/_components/provider/ReactQueryProvider";
import ReduxProvider from "./_lib/redux/ReduxProvider";
import AppProvider from "./(NextClient)/_components/AppProvider";
import CheckPathName from "./(NextClient)/_components/ui/CheckPathName";
import { Toaster } from "@/components/ui/toaster";
import DivNative from "./(NextClient)/_components/ui/NativeHtml/DivNative";
import Head from "next/head";
import SidebarContextProvider from "./(NextClient)/(user)/dashboard/SidebarContext";
import CheckExprireToken from "./(NextClient)/_components/Layout/CheckExprireToken";
import ToastProvider from "./(NextClient)/_components/provider/ToastProvider";
import { MutationCache, QueryCache, QueryClient } from "@tanstack/react-query";

const inter = Inter({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
	title: "Form builder",
	description: "Generated by create next app",
	icons: {
		icon: "/icon_core.png",
	},
};

type TProps = {
	children: React.ReactNode;
};

export default function RootLayout(props: TProps) {
	return (
		<html lang="vi" suppressHydrationWarning={true}>
			<head></head>
			<body className={inter.className}>
				<ReduxProvider>
					<ReactQueryProvider>
						<SidebarContextProvider>
							<AppProvider>{props.children}</AppProvider>
							<ToastProvider />
						</SidebarContextProvider>
					</ReactQueryProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
